// THE SWAPPABLE VENDORING LAYER.
// Today: feed the playground a self-contained @mycl/core build: a JS bundle (run
// in the iframe) and a bundled .d.ts (Monaco IntelliSense), covering both the
// main entry and /helpers (before/after/pipe/handleError aren't on main). Both
// are generated by scripts/build-playground-bundle.mjs from the workspace source.
//
// After npm publish: the JS bundle can be replaced with the published package
// (import-map → CDN/esm.sh) and the types with the published .d.ts. Page example
// source (import { createFnChannel } from '@mycl/core') never changes either way.
import myclBundle from './vendor/mycl-core.bundle.js?raw';
import myclTypes from './vendor/mycl-core.bundle.d.ts?raw';

export { myclBundle, myclTypes };

/** Minimal package.json so Monaco resolves `import … from '@mycl/core'` to the types. */
export const myclPackageJson = JSON.stringify({
  name: '@mycl/core',
  version: '0.0.0',
  types: 'index.d.ts',
  module: 'index.js',
});
